### ISSUE TITLE
File Names

### ISSUE THREAD

**Issue by michael-ava-dev** [mdsaifurrahmann/mac-android-flash-tool#2]
for my Poco F4, I had to rename the variable flash_all_except_data_storage.sh to flash_all_except_storage.sh 
<img width="1240" alt="Screenshot 2024-03-10 at 16 33 52" src="https://github.com/mdsaifurrahmann/mac-android-flash-tool/assets/121739686/778f4260-1a77-44ca-a03d-91e886e2b7cc"> and works fine

**Comment by mdsaifurrahmann** [comment]
@MichaelVelascoAmaya Thanks for letting me know. I'll fix this issue ASAP

**Comment by theryukverse** [comment]
for Mi A2 Global file name is `flash_all_except_data.sh`

**Comment by mdsaifurrahmann** [comment]
> for Mi A2 Global file name is `flash_all_except_data.sh`

Thank you for this information. I'll fix this ASAP.

**Comment by mdsaifurrahmann** [comment]
I've updated the file regarding your issue. Thanks for letting me know the problem. Give it a try now.
@MichaelVelascoAmaya @ravitejalam
