### ISSUE TITLE
[BUG] Requested download size is more than max allowed

### ISSUE THREAD

**Issue by t2hv33** [mdsaifurrahmann/mac-android-flash-tool#3]
1. Flash without lock bootloader
2. product: fuxi - Mi 13
![M1- 2024-08-18 at 18 20 30@2x](https://github.com/user-attachments/assets/427db502-f035-4f02-953b-062da1c48741)
![M1- 2024-08-18 at 18 21 11@2x](https://github.com/user-attachments/assets/5b132325-5172-4238-a385-f858ddb85003)

```
(bootloader) Partition vbmeta_system_b flashed successfully
OKAY [  0.002s]
Finished. Total time: 0.039s
Erasing 'metadata'                                 OKAY [  0.057s]
Finished. Total time: 0.068s
Sending 'metadata' (2184 KB)                       OKAY [  0.052s]
Writing 'metadata'                                 OKAY [  0.477s]
Finished. Total time: 0.562s
Sending 'userdata' (3860 KB)                       OKAY [  0.091s]
Writing 'userdata'                                 OKAY [  0.006s]
Finished. Total time: 0.129s
Sending 'cust' (2097152 KB)                        FAILED (remote: 'Requested download size is more than max allowed
')
fastboot: error: Command failed
Flash cust error
```

**Comment by t2hv33** [comment]
- UPDATE I do not use this tool
- I run the file directly in the rom file
![M1- 2024-08-18 at 18 33 37@2x](https://github.com/user-attachments/assets/32e83123-2e32-4e9e-a6e6-543b340585ba)
![M1- 2024-08-18 at 18 34 21@2x](https://github.com/user-attachments/assets/04a9ba99-58ee-4a8e-ad91-98a02635c9d8)

**Comment by mdsaifurrahmann** [comment]
@t2hv33 Would you kindly confirm that you did not alter this repository's source file? In any case, it shouldn't have happened. Every time I make changes to this repository, I run a real test.

```
Sending 'cust' (2097152 KB)                        FAILED (remote: 'Requested download size is more than max allowed
')
```

Your phone could be the source of this issue. This script has nothing to do with the error.

About the grep problem, as far as I'm aware, grep doesn't have a P option, so I never used the -- P flag anywhere.

Would you kindly explain to me how to replicate this issue? in order for me to verify on my end.
